# Generated by Django 4.0 on 2022-06-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extranotice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extranotice',
            name='is_image',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
